project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Toothsome Games"
  repo-url: https://github.com/toothsome-games/toothsome-games.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - text: "People"
        menu: 
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/toothsome-games/toothsome-games.github.io
  page-footer: 
    center: "Copyright &copy; 2026, Nick J Lyon"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false